require('dotenv').config()
const express = require("express")
const mongoose = require('mongoose')
const app = express();
const userRoute=require("./routes/user")
const authRoute=require("./routes/auth")
const productRoute=require("./routes/product")
const cartRoute=require("./routes/cart")
const orderRoute=require("./routes/order")
const stripeRoute=require("./routes/stripe")
const weatherRoute=require("./routes/weather")
const ratingRoute = require("./routes/rating")
const todoRoute = require("./routes/todo")
const cors = require("cors")
app.use(express.json());
// app.use(bodyParser.urlencoded({extended: true}))
mongoose.set('strictQuery', false);
 mongoose.connect(process.env.MONGO_URL,{ useNewUrlParser: true })
    .then(()=>{console.log("Connect to cloud db successfully")})
app.use(cors())
app.use("/api/checkout",stripeRoute)
app.use("/api/users",userRoute)   
app.use("/api/products",productRoute)   
app.use("/api/auth",authRoute)
app.use("/api/carts",cartRoute)
app.use("/api/orders",orderRoute)
app.use("/api/weather",weatherRoute)
app.use("/api/ratings",ratingRoute)
app.use("/api/todos", todoRoute)
app.listen(process.env.PORT||5001,()=>{
    console.log("Connect to port 5000 successfully");
})